'use strict';
(() => {
  const $ = id => document.getElementById(id);
  const esc = value => String(value ?? '').replace(/[&<>"']/g, char => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
  const c = window.PITCH_CONTENT;
  const notes = window.PITCH_NOTES;
  const evidence = window.PITCH_EVIDENCE || {candidates: [], chart1: [], chart2: []};
  const slidesCount = 6;
  let index = Math.max(0, Math.min(5, (Number(location.hash.slice(1)) || 1) - 1));
  let elapsed = 0, runningSince = null, selectedId = null, demoLoadedURL = null;
  const visited = new Set([index]);
  const prettyTime = seconds => `${Math.floor(seconds / 60)}:${String(Math.floor(seconds % 60)).padStart(2, '0')}`;
  const signed = value => `${value > 0 ? '+' : value < 0 ? '−' : ''}${Math.abs(value).toFixed(1)}`;
  const plots = Array.from({length:32}, (_, i) => `<i class="plot ${i >= 16 ? 'lost' : ''}"></i>`).join('');

  function render() {
    const slides = [
      `<div class="split"><div class="hero-copy"><span class="eyebrow">01 / THE CHOICE</span><h1>Half the plots.<br><em>A whole season<br>on the line.</em></h1><p class="lede">The budget just got cut. Hundreds of maize lines still need a chance.</p><p class="problem">Choose the lines worth testing before scarce plots become a wasted season.</p><div class="team-line"><strong>${esc(c.team)}</strong><br>${esc(c.members)}</div></div><div class="field-scene" aria-label="Illustrative field map: half of 32 drawn plots remain available. This is the story scenario, not model data."><div class="field-meta"><span>FIELD ALLOCATION</span><span>SEASON 01</span></div><div class="plot-grid" aria-hidden="true">${plots}</div><div class="field-caption"><strong>½</strong><span>the capacity.<br>The same hard choice.</span></div><span class="small-label">ILLUSTRATIVE BUDGET-CUT SCENARIO</span></div></div>`,
      `<div class="slide-heading"><span class="eyebrow">02 / OUR TASK & APPROACH</span><h2>Which lines deserve a plot?</h2></div><div class="approach-layout"><div class="target"><span class="eyebrow">WHAT WE PREDICT</span><div class="trait">${esc(c.target)}</div><p>${esc(c.targetExplanation)}</p><p class="source-note">${esc(c.targetFootnote)}</p></div><div class="angle"><span class="eyebrow">WHAT WE TEST DIFFERENTLY</span><h3>${esc(c.angleTitle)}</h3><p>${esc(c.angleExplanation)}</p><p class="source-note">${esc(c.angleFootnote)}</p></div></div>`,
      `<div class="slide-heading"><span class="eyebrow">03 / DATA & METHOD</span><h2>A test of what the model has not seen</h2></div><div class="method-flow"><div class="data-inputs">${c.inputs.map(([title,detail])=>`<div class="data-node"><h3>${esc(title)}</h3><small>${esc(detail)}</small></div>`).join('')}</div><div class="flow-arrow" aria-hidden="true">→</div><div class="model-node"><span class="eyebrow">FIT / COMPARE</span><h3>${esc(c.modelTitle)}</h3><p>${esc(c.modelCopy)}</p></div><div class="flow-arrow" aria-hidden="true">→</div><div class="decision-node"><span class="eyebrow">RANK / EVALUATE</span><h3>${esc(c.outputTitle)}</h3><p>${esc(c.outputCopy)}</p></div></div><div class="validation">${c.validation.map(([title,copy])=>`<div><strong>${esc(title)}</strong><p>${esc(copy)}</p></div>`).join('')}</div>`,
      `<div class="slide-heading"><span class="eyebrow">04 / KEY RESULTS · VERIFIED SAVED YIELD OUTPUT</span><h2>${esc(c.resultsTitle)}</h2></div><div class="charts"><div class="chart-card"><h3>${esc(c.chartTitles[0])}</h3><div id="chart-1"></div></div><div class="chart-card"><h3>${esc(c.chartTitles[1])}</h3><div id="chart-2"></div></div></div><div class="result-summary"><div class="result-number">${esc(c.accuracy)} <small>${esc(c.accuracyUnit)}</small></div><p class="negative">${esc(c.resultSummary)}</p></div>`,
      `<div class="slide-heading"><span class="eyebrow">05 / WHAT IT MEANS</span><h2>What It Means</h2></div><div class="meaning-example"><div class="meaning-decision"><div class="meaning-icon decision-icon">A</div><div><h3>No production lines advance</h3><p>The locked Top-50 result was −4.70 bu/acre. Line MAE was 8.84 bu/acre, and the ranking did not earn a production recommendation.</p><div class="line-ids">Exploratory retest only:<br>${c.lineIds.map(esc).join('<br>')}</div></div></div><section class="meaning-card opportunity-card"><div class="meaning-card-head"><span class="meaning-icon money-icon">$</span><h3>The opportunity</h3></div><strong>2,326 fewer plot-equivalents, conditionally</strong><p>A 50-line, two-site pilot would use 100 plot-equivalents instead of 2,426 for all 1,213 lines at one replicate. This analysis did not save plots or show genetic gain.</p></section><section class="meaning-card limits-card"><div class="meaning-card-head"><span class="meaning-icon limit-icon">!</span><h3>Limits and next step</h3></div><strong>Independent, population-balanced pilot</strong><p>Thirty-eight of 50 shortlist lines come from one population, and the two-site cohort covers 7.6% of tested 2008 lines. Predeclare sites, weights, budget, and uncertainty calibration.</p></section></div><div class="closing-line">${esc(c.closing)}</div>`,
      `<div class="slide-heading"><span class="eyebrow">AFTER THE FIVE-MINUTE PITCH / LIVE DEMO</span><h2>The FieldWise dashboard</h2></div><div class="demo-launch"><div><p class="lede">The timed presentation is complete. Now inspect the exploratory saved output in the working dashboard.</p><button class="primary large" id="launch-demo">Open the live workspace <span aria-hidden="true">↗</span></button><div class="demo-qr"><img src="demo-qr.png" alt="QR code for the FieldWise live dashboard"><div><strong>Scan me to follow along</strong><span>Open the dashboard on your phone during the demo.</span></div></div></div><div class="demo-preview"><div class="preview-top"><strong>FieldWise / Candidate explorer</strong><span>POST-PITCH DEMO</span></div><div class="preview-row"><span>01</span>Open ranked lines<em>Compare scores</em></div><div class="preview-row"><span>02</span>Select a candidate<em>Inspect detail</em></div><div class="preview-row"><span>03</span>Return to evidence<em>Discuss limits</em></div></div></div>`
    ];
    $('deck').innerHTML = slides.map((html,i)=>`<section class="slide" id="slide-${i+1}" role="group" aria-roledescription="slide" aria-label="${i+1} of ${slidesCount}: ${notes.labels[i]}">${html}</section>`).join('');
    $('field-nav').innerHTML = notes.labels.map((label,i)=>`<button data-slide="${i}" title="${esc(label)}" aria-label="Slide ${i+1}: ${esc(label)}">${String(i+1).padStart(2,'0')}<span>${['Choice','Approach','Method','Results','Decision','Demo'][i]}</span></button>`).join('');
    $('launch-demo').addEventListener('click', openDemo);
    renderCharts(); show(index, false);
  }
  function show(next, changeHash=true) {
    index=Math.max(0,Math.min(5,next)); visited.add(index);
    document.querySelectorAll('.slide').forEach((slide,i)=>{slide.classList.toggle('active',i===index);slide.setAttribute('aria-hidden',String(i!==index));});
    document.querySelectorAll('[data-slide]').forEach((button,i)=>{button.setAttribute('aria-current',String(i===index));button.classList.toggle('visited',visited.has(i));});
    $('page-count').textContent=`${String(index+1).padStart(2,'0')} / 06`;
    $('previous').disabled=index===0; $('next').disabled=index===5;
    if(changeHash)history.replaceState(null,'',`#${index+1}`);
    const start=notes.budgets.slice(0,index).reduce((a,b)=>a+b,0);
    $('notes-timing').textContent=index===5?'POST-PITCH DEMO · timer paused':`SECTION ${index+1} · ${notes.budgets[index]}s · ${prettyTime(start)}–${prettyTime(start+notes.budgets[index])} · Finish by 5:00`;
    $('notes-copy').innerHTML=`<p>${esc(notes.scripts[index])}</p>${index<5?`<p class="source-note">${esc(c.source)}</p>`:''}`;
    $('announcement').textContent=`Slide ${index+1}: ${notes.labels[index]}`;
  }
  function chartSVG({title,series,groups,xLabel,yLabel,min,max,ticks}) {
    const w=510,h=264,left=61,right=17,top=35,bottom=50,pw=w-left-right,ph=h-top-bottom;
    const y=value=>top+(max-value)/(max-min)*ph;
    const tx=(x,yy,value,extra='')=>`<text x="${x}" y="${yy}" fill="#53654f" font-family="Segoe UI,sans-serif" font-size="13" ${extra}>${esc(value)}</text>`;
    let svg=`<svg viewBox="0 0 ${w} ${h}" role="img" aria-label="${esc(title)}"><title>${esc(title)}</title><desc>${esc(series.map(s=>`${s.label}: ${s.values.map((v,i)=>`${groups[i]} ${v.toFixed(2)} bu/acre`).join(', ')}`).join('. '))}</desc>${tx(left,17,yLabel,'font-size="12"')}`;
    for(const tick of ticks)svg+=`<line x1="${left}" y1="${y(tick)}" x2="${w-right}" y2="${y(tick)}" stroke="${tick===0?'#7a8d6e':'#d9dfcf'}" ${tick===0?'':'stroke-dasharray="2 4"'}/>${tx(left-9,y(tick)+4,tick,'text-anchor="end"')}`;
    const groupWidth=pw/groups.length;
    groups.forEach((group,i)=>{const barWidth=Math.min(36,groupWidth/(series.length+1.8));series.forEach((s,j)=>{const value=s.values[i],x=left+groupWidth*(i+.5)+(j-(series.length-1)/2)*barWidth*1.15-barWidth/2;svg+=`<rect x="${x}" y="${Math.min(y(value),y(0))}" width="${barWidth}" height="${Math.max(1,Math.abs(y(value)-y(0)))}" fill="${s.color}" ${series.length===1&&group===50?'stroke="#173e2e" stroke-width="2"':''}><title>${esc(s.label)} · ${group}: ${value.toFixed(2)} bu/acre</title></rect>`;if(series.length===1)svg+=tx(x+barWidth/2,y(value)+17,signed(value),'text-anchor="middle"');});svg+=tx(left+groupWidth*(i+.5),h-bottom+23,group,'text-anchor="middle"');});
    return svg+tx(left+pw/2,h-6,xLabel,'text-anchor="middle"')+'</svg>';
  }
  function renderCharts() {
    if(evidence.chart1.length!==12||evidence.chart2.length!==4){['chart-1','chart-2'].forEach(id=>$(id).innerHTML='<p class="error-message">Saved chart evidence is unavailable. No values are substituted.</p>');return;}
    const policies=[['historical_baseline','Historical baseline','#aab79b'],['ridge_direct_256','Marker ridge','#c8a15a'],['risk_adjusted_historical','Risk-adjusted historical','#315840']], years=[2004,2005,2006,2007];
    const series=policies.map(([policy,label,color])=>({label,color,values:years.map(year=>evidence.chart1.find(r=>r.year===year&&r.policy===policy).gain)}));
    $('chart-1').innerHTML=chartSVG({title:c.chartTitles[0],series,groups:years,xLabel:'Held-out future year',yLabel:'Top-10% selection gain (bu/acre)',min:-10,max:20,ticks:[-10,0,10,20]})+`<div class="chart-legend">${series.map(s=>`<span style="--swatch:${s.color}">${esc(s.label)}</span>`).join('')}</div><p class="source-note">Saved pre-2008 validation · Phase 5 / chart1_data.csv</p>`;
    $('chart-2').innerHTML=chartSVG({title:c.chartTitles[1],series:[{label:'Locked 2008 selection gain',color:'#a2674a',values:evidence.chart2.map(r=>r.gain)}],groups:evidence.chart2.map(r=>r.budget),xLabel:'Lines selected for two-site testing',yLabel:'Selected yield − eligible mean (bu/acre)',min:-10,max:2,ticks:[-10,-5,0]})+'<div class="chart-legend"><span style="--swatch:#a2674a">Locked 2008</span><span>Outlined: fixed 50-line pilot</span></div><p class="source-note">Saved final evaluation · Phase 5 / chart2_data.csv</p>';
  }
  function updateClock(){const seconds=elapsed+(runningSince===null?0:(Date.now()-runningSince)/1000);$('clock').textContent=prettyTime(seconds);$('clock-button').classList.toggle('running',runningSince!==null);$('clock-button').classList.toggle('warning',seconds>=270&&seconds<300);$('clock-button').classList.toggle('overtime',seconds>=300);}
  function toggleClock(){if(runningSince===null)runningSince=Date.now();else{elapsed+=(Date.now()-runningSince)/1000;runningSince=null;}updateClock();}
  function pauseClock(){if(runningSince!==null){elapsed+=(Date.now()-runningSince)/1000;runningSince=null;updateClock();}}
  function toggleNotes(){$('notes').hidden=!$('notes').hidden;$('notes-button').setAttribute('aria-expanded',String(!$('notes').hidden));}
  async function toggleFullscreen(){try{if(document.fullscreenElement)await document.exitFullscreen();else await document.documentElement.requestFullscreen();}catch{$('announcement').textContent='Fullscreen is unavailable. Use your browser’s fullscreen control.';}}
  function setDemoPane(pane){const live=pane==='live';$('live-pane').hidden=!live;$('snapshot-pane').hidden=live;$('live-tab').classList.toggle('active',live);$('snapshot-tab').classList.toggle('active',!live);$('demo-status').textContent=live?'LIVE WEBSITE':'SAVED OUTPUT · YIELD';if(live&&demoLoadedURL!==c.dashboard){const url=new URL(c.dashboard);$('external-demo').href=url.href;url.searchParams.set('embed','true');$('dashboard-frame').src=url.href;demoLoadedURL=c.dashboard;}if(!live)renderCandidates();}
  function openDemo(){pauseClock();$('notes').hidden=true;$('demo-overlay').hidden=false;for(const selector of ['.masthead','#deck','.deck-footer','#notes'])document.querySelector(selector).inert=true;setDemoPane('live');$('return-demo').focus();}
  function closeDemo(){$('demo-overlay').hidden=true;for(const selector of ['.masthead','#deck','.deck-footer','#notes'])document.querySelector(selector).inert=false;$('launch-demo').focus();}
  function renderCandidates(){const query=$('line-search').value.toLowerCase().trim(),matched=evidence.candidates.filter(row=>`${row.id} ${row.population}`.toLowerCase().includes(query)),displayed=matched.slice(0,100);if(!displayed.some(row=>row.id===selectedId))selectedId=displayed[0]?.id||null;$('table-caption').textContent=`Showing ${displayed.length} of ${matched.length} matching candidates · fixed saved portfolio rank`;$('candidate-rows').innerHTML=displayed.length?displayed.map(row=>`<tr class="${row.id===selectedId?'selected':''}"><td>${row.rank}</td><td><button data-line="${esc(row.id)}">${esc(row.id)}</button></td><td>${row.predicted.toFixed(2)}</td><td>${row.score.toFixed(2)}</td></tr>`).join(''):'<tr><td colspan="4">No matching saved candidates.</td></tr>';renderDetail();}
  function renderDetail(){const row=evidence.candidates.find(candidate=>candidate.id===selectedId);if(!row){$('line-detail').innerHTML='<p>Select a candidate to inspect its saved score.</p>';return;}$('line-detail').innerHTML=`<span class="eyebrow">CANDIDATE DETAIL · RANK ${row.rank}</span><h3>${esc(row.id)}</h3><p>Population ${esc(row.population)}</p><dl><div><dt>Historical yield estimate</dt><dd>${row.predicted.toFixed(2)}</dd></div><div><dt>Risk-adjusted score</dt><dd>${row.score.toFixed(2)}</dd></div><div><dt>Model disagreement</dt><dd>${row.disagreement.toFixed(2)}</dd></div><div><dt>Score unit</dt><dd>bu/acre</dd></div></dl><p>Rule: historical yield estimate minus 1.0 × genomic-model disagreement. Disagreement is not a calibrated confidence interval.</p><div class="detail-status"><span class="eyebrow">${row.pilot?'EXPLORATORY RETEST CANDIDATE':'OUTSIDE THE FIXED 50-LINE PILOT'}</span><p>${esc(row.reason)}</p><p><strong>No production advancement recommendation.</strong></p></div><p class="source-note">Source: Phase 5 / final_recommendations.csv. Read-only snapshot. No new prediction or model run.</p>`;}
  $('field-nav').addEventListener('click',event=>{const button=event.target.closest('[data-slide]');if(button)show(Number(button.dataset.slide));});
  $('previous').addEventListener('click',()=>show(index-1)); $('next').addEventListener('click',()=>show(index+1)); $('notes-button').addEventListener('click',toggleNotes); $('notes-close').addEventListener('click',toggleNotes); $('clock-button').addEventListener('click',toggleClock); $('reset-clock').addEventListener('click',()=>{elapsed=0;runningSince=null;updateClock();}); $('fullscreen-button').addEventListener('click',toggleFullscreen); $('rubric-button').addEventListener('click',()=>$('rubric-dialog').showModal()); document.querySelectorAll('[data-close]').forEach(button=>button.addEventListener('click',()=>$(button.dataset.close).close())); $('return-demo').addEventListener('click',closeDemo); $('live-tab').addEventListener('click',()=>setDemoPane('live')); $('snapshot-tab').addEventListener('click',()=>setDemoPane('snapshot')); $('fallback-button').addEventListener('click',()=>setDemoPane('snapshot')); $('line-search').addEventListener('input',renderCandidates); $('candidate-rows').addEventListener('click',event=>{const button=event.target.closest('[data-line]');if(button){selectedId=button.dataset.line;renderDetail();}});
  window.addEventListener('hashchange',()=>show(Math.max(0,Math.min(5,(Number(location.hash.slice(1))||1)-1)),false));
  document.addEventListener('keydown',event=>{if(document.querySelector('dialog[open]'))return;if(event.key==='Escape'){if(!$('demo-overlay').hidden)closeDemo();else if(!$('notes').hidden)toggleNotes();return;}if(event.ctrlKey||event.altKey||event.metaKey||/INPUT|TEXTAREA|SELECT/.test(event.target.tagName)||!$('demo-overlay').hidden)return;const key=event.key.toLowerCase();if(['arrowright','arrowdown','pagedown',' '].includes(key)){event.preventDefault();show(index+1);}else if(['arrowleft','arrowup','pageup'].includes(key)){event.preventDefault();show(index-1);}else if(key==='home'){event.preventDefault();show(0);}else if(key==='end'){event.preventDefault();show(5);}else if(key==='n')toggleNotes();else if(key==='t')toggleClock();else if(key==='f')toggleFullscreen();else if(key==='d'){show(5);openDemo();}});
  render(); updateClock(); setInterval(updateClock,250);
})();

